name: Deploy
on:
  - push
  - pull_request

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
      
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      
      - name: Generate prisma
        run: pnpx prisma generate
      
      - name: Migrate prisma
        run: pnpx prisma
      
      - name: Install playwright utils
        run: pnpx playwright install

      - name: Build app
        run: pnpm build

      - name: Run local tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_svelte_kit
        run: pnpm test:e2e
      
      - name: Deploy to staging 
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
      
      - name: Test against staging
        env:
          DATABASE_URL: github.DATABASE_URL
          # VERCEL_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
        run: pnpm playwright test:e2e

      - name: Deploy to Production 
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' 
          scope: ${{ secrets.VERCEL_ORG_ID }}
